# Generated by Django 5.2.6 on 2025-09-30 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('michelinmap', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='name',
            new_name='c_name',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='name',
            new_name='r_name',
        ),
    ]
