# Generated by Django 5.2.6 on 2025-09-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('michelinmap', '0002_rename_name_city_c_name_rename_name_region_r_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='star',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
