# Generated by Django 5.2.6 on 2025-09-30 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('michelinmap', '0003_alter_restaurant_rating_alter_review_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='michelinmap.city'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='star',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
