# Generated by Django 5.2.6 on 2025-10-01 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('michelinmap', '0004_restaurant_city_alter_review_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='page',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
