# Generated by Django 5.2.6 on 2025-10-01 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('michelinmap', '0005_restaurant_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='price',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
