# Generated by Django 5.2.6 on 2025-10-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('michelinmap', '0006_restaurant_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='review_cnt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
