# Generated by Django 5.2.6 on 2025-10-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('michelinmap', '0007_restaurant_review_cnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
